application:
  port: 8080
database:
  host: "127.0.0.1"
  port: 5432
  username: "user"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@outlook.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
